services:
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: login_auth_template_test
    ports:
      - "5433:5432"
